version: "3.9"

services:
  shinyapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3838:3838"
    container_name: seqexpressionanalyser-app
    restart: unless-stopped
